# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FoodInfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QLabel

import time

class Ui_FoodInfoDialog(object):
    def __init__(self, pic=None, mat=None):
        super().__init__()
        if pic is not None:
            print("got pic in init of food info")
        else:
            print("empty in food info..")
        if pic is not None:
            self.tmpPicInDialog = pic
        if mat is not None:
            self.tmpMatInDialog = mat
        self.foodData = {
            'name': 'a',
            'calorie': 1,
            'carbo': 2,
            'protein': 3,
            'fat': 4,
            'sugar': 5,
            'sodium': 6
            }
        self.btnToStore = QPushButton("store")
        self.btnToCancel = QPushButton("cancel")

        self.tmpPicInDialog = None
        self.tmpMatInDialog = None
        self.timeList = None
        self.currentTime = None
        self.timeList = self.getTime()
        self.time_str = [str(i) for i in self.timeList]

        if pic is not None:
            print("pic is not None in abstract")
            self.tmpPicInDialog = pic

#        if self.tmpPicInDialog is not None:
#            self.label.setPixmap(self.tmpPicInDialog)
        else:
            print("empty!")

    def setImageLabel(self, pic):
        return self.label.setPixmap(pic)

    def getTime(self) -> time:
        tm = time.localtime(time.time())
        returnList = [tm.tm_mon, tm.tm_mday, tm.tm_hour, tm.tm_min]
        return returnList

    def getPicAndMatData(self, pic, mat):
        self.tmpPicInDialog = pic
        self.tmpMatInDialog = mat

    def setFoodFrame(self):
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 3000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 3000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.date = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.date.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setFrame(False)
        self.date.setObjectName("date")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 30, 261, 3000))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.food_frame = QtWidgets.QFrame(self.frame)
        self.food_frame.setGeometry(QtCore.QRect(10, 10, 240, 95))
        self.food_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.food_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.food_frame.setObjectName("food_frame")
        self.title_food_name = QtWidgets.QLineEdit(self.food_frame)
        self.title_food_name.setGeometry(QtCore.QRect(10, 10, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.title_food_name.setFont(font)
        self.title_food_name.setFrame(False)
        self.title_food_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_food_name.setDragEnabled(False)
        self.title_food_name.setReadOnly(True)
        self.title_food_name.setObjectName("title_food_name")
        self.title_volumn = QtWidgets.QLineEdit(self.food_frame)
        self.title_volumn.setGeometry(QtCore.QRect(10, 40, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title_volumn.setFont(font)
        self.title_volumn.setFrame(False)
        self.title_volumn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_volumn.setDragEnabled(False)
        self.title_volumn.setReadOnly(True)
        self.title_volumn.setObjectName("title_volumn")
        self.food_name = QtWidgets.QLineEdit(self.food_frame)
        self.food_name.setGeometry(QtCore.QRect(110, 10, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.food_name.setFont(font)
        self.food_name.setFrame(False)
        self.food_name.setObjectName("food_name")
        self.volumn = QtWidgets.QComboBox(self.food_frame)
        self.volumn.setGeometry(QtCore.QRect(110, 40, 111, 20))
        self.volumn.setObjectName("volumn")
        self.volumn.addItem("")
        self.volumn.addItem("")
        self.volumn.addItem("")
        self.select_button = QtWidgets.QPushButton(self.food_frame)
        self.select_button.setGeometry(QtCore.QRect(178, 68, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_button.setFont(font)
        self.select_button.setStyleSheet("background-color:rgb(200,200,200);\n"
"border-radius:5px")
        self.select_button.setObjectName("select_button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)


    def setupUi(self, FoodInfoDialog):
        FoodInfoDialog.setObjectName("FoodInfoDialog")
        FoodInfoDialog.resize(720, 540)
        self.currentTime = QLabel(' '.join(self.time_str))

        self.picture = QtWidgets.QLabel(FoodInfoDialog)
        self.picture.setGeometry(QtCore.QRect(40, 30, 381, 300))
        self.picture.setText("")
        self.picture.setTextFormat(QtCore.Qt.PlainText)
        self.picture.setPixmap(QtGui.QPixmap("../Controller_Suengkwon/image.jpeg"))
        self.picture.setObjectName("picture")
        self.nutrition_frame = QtWidgets.QFrame(FoodInfoDialog)
        self.nutrition_frame.setGeometry(QtCore.QRect(32, 390, 572, 51))
        self.nutrition_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nutrition_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nutrition_frame.setObjectName("nutrition_frame")
        self.nutrition_table = QtWidgets.QTableWidget(self.nutrition_frame)
        self.nutrition_table.setGeometry(QtCore.QRect(0, 0, 572, 51))
        self.nutrition_table.setStyleSheet("background-color:rgb(200, 230, 255);")
        self.nutrition_table.setGridStyle(QtCore.Qt.NoPen)
        self.nutrition_table.setWordWrap(True)
        self.nutrition_table.setRowCount(1)
        self.nutrition_table.setColumnCount(6)
        self.nutrition_table.setObjectName("nutrition_table")
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 5, item)
        self.nutrition_table.horizontalHeader().setVisible(True)
        self.nutrition_table.horizontalHeader().setDefaultSectionSize(95)
        self.nutrition_table.horizontalHeader().setMinimumSectionSize(60)
        self.nutrition_table.verticalHeader().setVisible(False)
        self.nutrition_table.verticalHeader().setCascadingSectionResizes(False)
        self.nutrition_table.verticalHeader().setDefaultSectionSize(31)
        self.nutrition_table.verticalHeader().setHighlightSections(True)
        self.nutrition_table.verticalHeader().setMinimumSectionSize(20)
        self.nutrition = QtWidgets.QLineEdit(FoodInfoDialog)
        self.nutrition.setGeometry(QtCore.QRect(30, 360, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.nutrition.setFont(font)
        self.nutrition.setFrame(False)
        self.nutrition.setObjectName("nutrition")

        self.btnToStore = QtWidgets.QPushButton(FoodInfoDialog)
        self.btnToStore.setGeometry(QtCore.QRect(480, 370, 89, 25))
        self.btnToStore.setObjectName("pushButton")
        self.btnToCancel = QtWidgets.QPushButton(FoodInfoDialog)
        self.btnToCancel.setGeometry(QtCore.QRect(600, 370, 89, 25))
        self.btnToCancel.setObjectName("pushButton_2")


        self.label = QtWidgets.QLabel(FoodInfoDialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 400, 300))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/jellyfish.jpg"))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(FoodInfoDialog)
        self.scrollArea.setGeometry(QtCore.QRect(410, 10, 275, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.setFoodFrame()

        self.retranslateUi(FoodInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(FoodInfoDialog)

    def retranslateUi(self, FoodInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        FoodInfoDialog.setWindowTitle(_translate("FoodInfoDialog", "Dialog"))
        item = self.nutrition_table.horizontalHeaderItem(0)
        item.setText(_translate("FoodInfoDialog", "Calories[kcal]"))
        item = self.nutrition_table.horizontalHeaderItem(1)
        item.setText(_translate("FoodInfoDialog", "Carbo[g]"))
        item = self.nutrition_table.horizontalHeaderItem(2)
        item.setText(_translate("FoodInfoDialog", "Protein[g]"))
        item = self.nutrition_table.horizontalHeaderItem(3)
        item.setText(_translate("FoodInfoDialog", "Fat[g]"))
        item = self.nutrition_table.horizontalHeaderItem(4)
        item.setText(_translate("FoodInfoDialog", "Sugar[g]"))
        item = self.nutrition_table.horizontalHeaderItem(5)
        item.setText(_translate("FoodInfoDialog", "Sodium[g]"))
        __sortingEnabled = self.nutrition_table.isSortingEnabled()
        self.nutrition_table.setSortingEnabled(False)
        item = self.nutrition_table.item(0, 0)
        item.setText(_translate("FoodInfoDialog", "406"))
        item = self.nutrition_table.item(0, 1)
        item.setText(_translate("FoodInfoDialog", "147.8"))
        item = self.nutrition_table.item(0, 2)
        item.setText(_translate("FoodInfoDialog", "46.4"))
        item = self.nutrition_table.item(0, 3)
        item.setText(_translate("FoodInfoDialog", "26.4"))
        item = self.nutrition_table.item(0, 4)
        item.setText(_translate("FoodInfoDialog", "4.6"))
        item = self.nutrition_table.item(0, 5)
        item.setText(_translate("FoodInfoDialog", "3.2"))
        self.nutrition_table.setSortingEnabled(__sortingEnabled)
        self.nutrition.setText(_translate("FoodInfoDialog", "Nutritional Information"))

        self.date.setText(_translate("FoodInfoDialog", "2023/11/24   12:08"))
        self.title_food_name.setText(_translate("FoodInfoDialog", "Food Name"))
        self.title_volumn.setText(_translate("FoodInfoDialog", "Volumn"))
        self.food_name.setText(_translate("FoodInfoDialog", "Kimchi jjigae"))
        self.volumn.setItemText(0, _translate("FoodInfoDialog", "150g"))
        self.volumn.setItemText(1, _translate("FoodInfoDialog", "200g(1person)"))
        self.volumn.setItemText(2, _translate("FoodInfoDialog", "250g"))
        self.select_button.setText(_translate("FoodInfoDialog", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FoodInfoDialog = QtWidgets.QDialog()
    ui = Ui_FoodInfoDialog()
    ui.setupUi(FoodInfoDialog)
    FoodInfoDialog.show()
    sys.exit(app.exec_())
