# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuInfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuInfoDialog(object):
    def setupUi(self, MenuInfoDialog):
        MenuInfoDialog.setObjectName("MenuInfoDialog")
        MenuInfoDialog.resize(720, 540)
        self.label = QtWidgets.QLabel(MenuInfoDialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 291, 431))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/menu.jpg"))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(MenuInfoDialog)
        self.scrollArea.setGeometry(QtCore.QRect(360, 10, 331, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 315, 3000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 3000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.date = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.date.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setFrame(False)
        self.date.setObjectName("date")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 29, 311, 3001))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.food_frame = QtWidgets.QFrame(self.frame)
        self.food_frame.setGeometry(QtCore.QRect(10, 10, 301, 51))
        self.food_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.food_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.food_frame.setObjectName("food_frame")
        self.title_food_name = QtWidgets.QLineEdit(self.food_frame)
        self.title_food_name.setGeometry(QtCore.QRect(10, 4, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.title_food_name.setFont(font)
        self.title_food_name.setFrame(False)
        self.title_food_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_food_name.setDragEnabled(False)
        self.title_food_name.setReadOnly(True)
        self.title_food_name.setObjectName("title_food_name")
        self.title_calories = QtWidgets.QLineEdit(self.food_frame)
        self.title_calories.setGeometry(QtCore.QRect(10, 27, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title_calories.setFont(font)
        self.title_calories.setFrame(False)
        self.title_calories.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_calories.setDragEnabled(False)
        self.title_calories.setReadOnly(True)
        self.title_calories.setObjectName("title_calories")
        self.food_name = QtWidgets.QLineEdit(self.food_frame)
        self.food_name.setGeometry(QtCore.QRect(110, 4, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.food_name.setFont(font)
        self.food_name.setFrame(False)
        self.food_name.setObjectName("food_name")
        self.select_button = QtWidgets.QPushButton(self.food_frame)
        self.select_button.setGeometry(QtCore.QRect(240, 16, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_button.setFont(font)
        self.select_button.setStyleSheet("background-color:rgb(200,200,200);\n"
"border-radius:5px")
        self.select_button.setObjectName("select_button")
        self.calories = QtWidgets.QLineEdit(self.food_frame)
        self.calories.setGeometry(QtCore.QRect(110, 28, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calories.setFont(font)
        self.calories.setFrame(False)
        self.calories.setObjectName("calories")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(MenuInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(MenuInfoDialog)

    def retranslateUi(self, MenuInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        MenuInfoDialog.setWindowTitle(_translate("MenuInfoDialog", "Dialog"))
        self.date.setText(_translate("MenuInfoDialog", "2023/11/24   12:08"))
        self.title_food_name.setText(_translate("MenuInfoDialog", "Food Name"))
        self.title_calories.setText(_translate("MenuInfoDialog", "Calories"))
        self.food_name.setText(_translate("MenuInfoDialog", "Kimchi jjigae"))
        self.select_button.setText(_translate("MenuInfoDialog", "Select"))
        self.calories.setText(_translate("MenuInfoDialog", "612kcal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuInfoDialog = QtWidgets.QDialog()
    ui = Ui_MenuInfoDialog()
    ui.setupUi(MenuInfoDialog)
    MenuInfoDialog.show()
    sys.exit(app.exec_())
