# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuInfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuInfoDialog(object):
    def __init__(self, pic=None, mat=None, foodList=None):
        super().__init__()
        if pic is None:
            print("empty in food info..")
        if pic is not None:
            self.tmpPicInDialog = pic
        if mat is not None:
            self.tmpMatInDialog = mat
        self.tmpPicInDialog = None
        self.tmpMatInDialog = None

        if pic is not None:
            self.tmpPicInDialog = pic
        else:
            print("empty!")

        self.count = 1


        # self.database = (("kimchi jjigae","300","10","20","30","40","50","60"), ("galbi","200","11","21","31","41","51","61"))
        self.database = [["kimchi JJigae", "300", "10", "20", "30", "40", "50", "60"]]
        self.chgData(foodList)

    def chgData(self, foodList):
        self.count = len(foodList)
        # print("foodList:", foodList)
        self.database = []
        for i, elem in enumerate(foodList):
            tmpList = []
            tmpList.append(str(elem['food_name']))
            tmpList.append(i+1)
            tmpList.append(elem['calorie'])
            tmpList.append(elem['carbo'])
            tmpList.append(elem['protein'])
            tmpList.append(elem['fat'])
            tmpList.append(elem['sugar'])
            tmpList.append(elem['sodium'])
            tmpList.append(0)  # chk For select Clicked
            self.database.append(tmpList)
        # print("database:", self.database)

    def setImageLabel(self, pic):
        return self.label.setPixmap(pic)

    def getPicAndMatData(self, pic, mat):
        self.tmpPicInDialog = pic
        self.tmpMatInDialog = mat

    def chgCnt(self, number):
        self.count = number

    def setMenuFrame(self, x):
        food_frame = QtWidgets.QFrame(self.frame)
        food_frame.setGeometry(QtCore.QRect(10, x, 300, 50))
        food_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        food_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        food_frame.setObjectName("food_frame")
        title_food_name = QtWidgets.QLineEdit(food_frame)
        title_food_name.setGeometry(QtCore.QRect(10, 4, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        title_food_name.setFont(font)
        title_food_name.setFrame(False)
        title_food_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        title_food_name.setDragEnabled(False)
        title_food_name.setReadOnly(True)
        title_food_name.setObjectName("title_food_name")
        title_calories = QtWidgets.QLineEdit(food_frame)
        title_calories.setGeometry(QtCore.QRect(10, 27, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        title_calories.setFont(font)
        title_calories.setFrame(False)
        title_calories.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        title_calories.setDragEnabled(False)
        title_calories.setReadOnly(True)
        title_calories.setObjectName("title_calories")
        food_name = QtWidgets.QLineEdit(food_frame)
        food_name.setGeometry(QtCore.QRect(110, 4, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        food_name.setFont(font)
        food_name.setFrame(False)
        food_name.setObjectName("food_name")
        select_button = QtWidgets.QPushButton(food_frame)
        select_button.setGeometry(QtCore.QRect(240, 16, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        select_button.setFont(font)
        select_button.setStyleSheet("background-color:rgb(200,200,200);\n"
        "border-radius:5px")
        select_button.setObjectName("select_button")
        calories = QtWidgets.QLineEdit(food_frame)
        calories.setGeometry(QtCore.QRect(110, 27, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        calories.setFont(font)
        calories.setFrame(False)
        calories.setObjectName("calories")

        _translate = QtCore.QCoreApplication.translate
        title_food_name.setText(_translate("MenuInfoDialog", "Food Name"))
        title_calories.setText(_translate("MenuInfoDialog", "Calories"))
        select_button.setText(_translate("MenuInfoDialog", "Select"))

        self.food_name_list.append(food_name)
        self.calories_list.append(calories)
        self.select_button_list.append(select_button)

    def selectButtonTo(self, x):
        _translate = QtCore.QCoreApplication.translate
        item = self.nutrition_table.item(0, 0)
        # item.setText(_translate("FoodInfoDialog", self.database[x][2]))
        item.setText(_translate("FoodInfoDialog", self.database[x][2]))
        item = self.nutrition_table.item(0, 1)
        item.setText(_translate("FoodInfoDialog", self.database[x][3]))
        item = self.nutrition_table.item(0, 2)
        item.setText(_translate("FoodInfoDialog", self.database[x][4]))
        item = self.nutrition_table2.item(0, 0)
        item.setText(_translate("FoodInfoDialog", self.database[x][5]))
        item = self.nutrition_table2.item(0, 1)
        item.setText(_translate("FoodInfoDialog", self.database[x][6]))
        item = self.nutrition_table2.item(0, 2)
        item.setText(_translate("FoodInfoDialog", self.database[x][7]))

        # for chk to Store
        self.database[x][8] = 1


    def setupUi(self, MenuInfoDialog):
        MenuInfoDialog.setObjectName("MenuInfoDialog")
        MenuInfoDialog.resize(720, 540)
        self.label = QtWidgets.QLabel(MenuInfoDialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 300, 470))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        # self.label.setPixmap(QtGui.QPixmap("../../../Downloads/menu.jpg"))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(MenuInfoDialog)
        self.scrollArea.setGeometry(QtCore.QRect(360, 30, 331, 340))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 315, 3000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 3000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 311, 3000))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.food_name_list = []
        self.calories_list = []
        self.select_button_list = []

        j = 10
        for i in range(self.count):
            self.setMenuFrame(j)
            j += 55

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)


        self.nutrition_frame = QtWidgets.QFrame(MenuInfoDialog)
        self.nutrition_frame.setGeometry(QtCore.QRect(360, 400, 332, 100))
        self.nutrition_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nutrition_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nutrition_frame.setObjectName("nutrition_frame")

        self.nutrition_table = QtWidgets.QTableWidget(self.nutrition_frame)
        self.nutrition_table.setGeometry(QtCore.QRect(0, 0, 332, 50))
        self.nutrition_table.setStyleSheet("background-color:rgb(100, 150, 255);")
        self.nutrition_table.setGridStyle(QtCore.Qt.NoPen)
        self.nutrition_table.setWordWrap(True)
        self.nutrition_table.setRowCount(1)
        self.nutrition_table.setColumnCount(3)
        self.nutrition_table.setObjectName("meal_info")
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table.setItem(0, 2, item)
        self.nutrition_table.horizontalHeader().setVisible(True)
        self.nutrition_table.horizontalHeader().setDefaultSectionSize(110)
        self.nutrition_table.horizontalHeader().setMinimumSectionSize(60)
        self.nutrition_table.verticalHeader().setVisible(False)
        self.nutrition_table.verticalHeader().setDefaultSectionSize(31)
        self.nutrition_table.verticalHeader().setHighlightSections(True)
        self.nutrition_table.verticalHeader().setMinimumSectionSize(20)
        self.nutrition_table2 = QtWidgets.QTableWidget(self.nutrition_frame)
        self.nutrition_table2.setGeometry(QtCore.QRect(0, 50, 362, 50))
        self.nutrition_table2.setStyleSheet("background-color:rgb(100, 150, 255);")
        self.nutrition_table2.setGridStyle(QtCore.Qt.NoPen)
        self.nutrition_table2.setWordWrap(True)
        self.nutrition_table2.setRowCount(1)
        self.nutrition_table2.setColumnCount(3)
        self.nutrition_table2.setObjectName("meal_info")
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nutrition_table2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.nutrition_table2.setItem(0, 2, item)
        self.nutrition_table2.horizontalHeader().setVisible(True)
        self.nutrition_table2.horizontalHeader().setDefaultSectionSize(110)
        self.nutrition_table2.horizontalHeader().setMinimumSectionSize(60)
        self.nutrition_table2.verticalHeader().setVisible(False)
        self.nutrition_table2.verticalHeader().setDefaultSectionSize(31)
        self.nutrition_table2.verticalHeader().setHighlightSections(True)
        self.nutrition_table2.verticalHeader().setMinimumSectionSize(20)
        self.nutrition = QtWidgets.QLineEdit(MenuInfoDialog)
        self.nutrition.setGeometry(QtCore.QRect(360, 373, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.nutrition.setFont(font)
        self.nutrition.setFrame(False)
        self.nutrition.setObjectName("nutrition")

        self.retranslateUi(MenuInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(MenuInfoDialog)

    def retranslateUi(self, MenuInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        MenuInfoDialog.setWindowTitle(_translate("MenuInfoDialog", "Dialog"))
        item = self.nutrition_table.horizontalHeaderItem(0)
        item.setText(_translate("FoodInfoDialog", "Calories[kcal]"))
        item = self.nutrition_table.horizontalHeaderItem(1)
        item.setText(_translate("FoodInfoDialog", "Carbo[g]"))
        item = self.nutrition_table.horizontalHeaderItem(2)
        item.setText(_translate("FoodInfoDialog", "Protein[g]"))
        item = self.nutrition_table2.horizontalHeaderItem(0)
        item.setText(_translate("FoodInfoDialog", "Fat[g]"))
        item = self.nutrition_table2.horizontalHeaderItem(1)
        item.setText(_translate("FoodInfoDialog", "Sugar[g]"))
        item = self.nutrition_table2.horizontalHeaderItem(2)
        item.setText(_translate("FoodInfoDialog", "Sodium[mg]"))
        item = self.nutrition_table.item(0, 0)
        item.setText(_translate("FoodInfoDialog", "0"))
        item = self.nutrition_table.item(0, 1)
        item.setText(_translate("FoodInfoDialog", "0"))
        item = self.nutrition_table.item(0, 2)
        item.setText(_translate("FoodInfoDialog", "0"))
        item = self.nutrition_table2.item(0, 0)
        item.setText(_translate("FoodInfoDialog", "0"))
        item = self.nutrition_table2.item(0, 1)
        item.setText(_translate("FoodInfoDialog", "0"))
        item = self.nutrition_table2.item(0, 2)
        item.setText(_translate("FoodInfoDialog", "0"))
        self.nutrition.setText(_translate("FoodInfoDialog", "Nutritional Information"))

        for i in range(self.count):
            self.food_name_list[i].setText(_translate("MenuInfoDialog", self.database[i][0]))
            self.calories_list[i].setText(_translate("MenuInfoDialog", self.database[i][2]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuInfoDialog = QtWidgets.QDialog()
    ui = Ui_MenuInfoDialog()
    ui.setupUi(MenuInfoDialog)
    MenuInfoDialog.show()
    sys.exit(app.exec_())
