# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DietWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
import cv2

class Ui_Gallery(object):
    def __init__(self):
        self.count = 0
        self.database = []
        self.food_img = []

    def setData(self, foodInfo: list, foodImg: list):
        # foodInfo : list of list(
        # day(eg.11271618) food_name serving calcorie carbo protein fat sugar sodium imgsize emptyspace) total 11
        # foodImg : list of Mat img
        self.count = len(foodInfo)
        self.database = []
        self.food_img = []
        for i in range(len(foodInfo)):
            self.temp = []
            self.food_img.append(foodImg[i])
            for j in range(len(foodInfo[i])-2):
                self.temp.append(foodInfo[i][j])
            self.database.append(self.temp)

    def setFrame(self, x, y, addr):
        meal = QtWidgets.QFrame(self.frame)
        meal.setGeometry(QtCore.QRect(x, y, 260, 230))
        meal.setFrameShadow(QtWidgets.QFrame.Raised)
        meal.setObjectName("meal")
        meal.setStyleSheet( "background-color:white;\n"
        "border-radius:5px;\n")

        picture = QtWidgets.QLabel(meal)
        picture.setGeometry(QtCore.QRect(10, 10, 240, 190))
        picture.setText("")
        picture.setObjectName("picture")

        height, width, channel = addr.shape
        bytes_per_line = 3 * width
        addr = cv2.cvtColor(addr, cv2.COLOR_BGR2RGB)
        q_image = QImage(addr.data, width, height, bytes_per_line, QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(q_image)
        new_pixmap = pixmap.scaled(241,191)
        picture.setPixmap(QtGui.QPixmap(new_pixmap))

        x_t = x+180
        y_t = y+200
        time = QtWidgets.QLineEdit(self.frame)
        time.setGeometry(QtCore.QRect(x_t, y_t, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        time.setFont(font)
        time.setStyleSheet("font-size:10px;\n"
        "background-color:white;")
        time.setFrame(False)
        time.setObjectName("time")

        self.picture_list.append(picture)
        self.time_list.append(time)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 770)

        self.gallery = QtWidgets.QLineEdit(Form)
        self.gallery.setGeometry(QtCore.QRect(370, 50, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.gallery.setFont(font)
        self.gallery.setFrame(False)
        self.gallery.setAlignment(QtCore.Qt.AlignCenter)
        self.gallery.setObjectName("lineEdit")

        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(80, 80, 710, 650))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet("background-color:rgb(225,230,230);\n")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 684, 3000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 3000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 710, 3000))
        self.frame.setMinimumSize(QtCore.QSize(0, 3000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.picture_list = []
        self.time_list = []
        y = 20
        for i in range(self.count):
            if i%2 == 0:
                self.setFrame(70, y, self.food_img[i])
            else:
                self.setFrame(390, y, self.food_img[i])
                y += 240

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gallery.setText(_translate("Form", "Gallery"))
        if self.count == len(self.database):
            for i in range(self.count):
                self.time_list[i].setText(_translate("TodayDietWindow", self.database[i][0][0:2]+" / "\
                +self.database[i][0][2:4]+"   "+self.database[i][0][4:6]+":"+self.database[i][0][6:8]))


