# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 600)
        self.layoutWidget = QtWidgets.QWidget(MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 110, 634, 395))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/jellyfish.jpg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_todayDiet = QtWidgets.QPushButton(self.splitter)
        self.pushButton_todayDiet.setObjectName("pushButton_todayDiet")
        self.pushButton_foodInfo = QtWidgets.QPushButton(self.splitter)
        self.pushButton_foodInfo.setObjectName("pushButton_foodInfo")
        self.pushButton_menuInfo = QtWidgets.QPushButton(self.splitter)
        self.pushButton_menuInfo.setObjectName("pushButton_menuInfo")
        self.pushButton_galleryView = QtWidgets.QPushButton(self.splitter)
        self.pushButton_galleryView.setObjectName("pushButton_galleryView")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Form"))
        self.pushButton_todayDiet.setText(_translate("MainWidget", "Today\'s Diet"))
        self.pushButton_foodInfo.setText(_translate("MainWidget", "Food Info"))
        self.pushButton_menuInfo.setText(_translate("MainWidget", "Menu Info"))
        self.pushButton_galleryView.setText(_translate("MainWidget", "gallery view"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWidget = QtWidgets.QWidget()
    ui = Ui_MainWidget()
    ui.setupUi(MainWidget)
    MainWidget.show()
    sys.exit(app.exec_())
